function pay(e) {
  if (e.isTrusted) {
    alert("paid");
  } else {
    alert("fraud");
  }
}

/*
The isTrusted read-only property of the Event interface is a boolean value that is true when the event was generated by the user agent (including via user actions and programmatic methods such as HTMLElement.focus()), and false when the event was dispatched via EventTarget.dispatchEvent(). The only exception is the click event, which initializes the isTrusted property to false in user agents.
*/

// The SVG Event.isTrusted property is a boolean that is true when the event was generated by a user action.
